# Generated by Django 5.0.1 on 2024-03-06 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_alter_labour_image_alter_manager_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='labour',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='labour',
            name='trade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMS.trades'),
        ),
    ]
