# Generated by Django 5.0.1 on 2024-03-06 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LMS', '0004_trades_labour_email_manager_email_labour_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('labour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LMS.labour')),
            ],
        ),
    ]
